services:
  mongodb:
    image: mongo:8.0
    container_name: jade-tipi-mongo
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jdtp
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    profiles:
      - mongodb

  mongo-express:
    image: mongo-express:latest
    container_name: jade-tipi-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    restart: unless-stopped
    profiles:
      - mongodb

volumes:
  mongodb_data:
