services:
  mongodb:
    image: mongo:8.0
    container_name: jade-tipi-mongo
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jdtp
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    profiles:
      - mongodb

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: jade-tipi-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: dev-mem
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:8484:8080"
    volumes:
      - ./jade-tipi-realm.json:/opt/keycloak/data/import/jade-tipi-realm.json:ro
    restart: unless-stopped

volumes:
  mongodb_data:
