/**
 * Part of Jade-Tipi — an open scientific metadata framework.
 *
 * Copyright (c) 2025 Duncan Scott and Jade-Tipi contributors
 * SPDX-License-Identifier: AGPL-3.0-only OR Commercial
 *
 * This file is part of a dual-licensed distribution:
 * - Under AGPL-3.0 for open-source use (see LICENSE)
 * - Under Commercial License for proprietary use (see DUAL-LICENSE.txt or contact licensing@jade-tipi.org)
 *
 * https://jade-tipi.org/license
 */
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.list

import org.junit.jupiter.api.Test

import static org.junit.jupiter.api.Assertions.*

class LinkedListTest {
    @Test void testConstructor() {
        def list = new LinkedList()
        assertEquals(0, list.size())
    }

    @Test void testAdd() {
        def list = new LinkedList()

        list.add('one')
        assertEquals(1, list.size())
        assertEquals('one', list.get(0))

        list.add('two')
        assertEquals(2, list.size())
        assertEquals('two', list.get(1))
    }

    @Test void testRemove() {
        def list = new LinkedList()

        list.add('one')
        list.add('two')
        assertTrue(list.remove('one'))

        assertEquals(1, list.size())
        assertEquals('two', list.get(0))

        assertTrue(list.remove('two'))
        assertEquals(0, list.size())
    }

    @Test void testRemoveMissing() {
        def list = new LinkedList()

        list.add('one')
        list.add('two')
        assertFalse(list.remove('three'))
        assertEquals(2, list.size())
    }
}
